### ISSUE TITLE
How to render JSX component in NodeContent ? 

### ISSUE THREAD

**Issue by kkkasio** [bumbeishvili/org-chart#115]
Hi friends, I came across this awesome lib for rendering hierarchies.
I'm using an integration with React, I have a question on how to render a JSX Component inside nodeContent.
Does anyone have this expertise ??

I understand that I can call an html template there, but I wouldn't want to do it that way. I would like to include a "Static" JSX that already contains my styling...

**Comment by bumbeishvili** [comment]
There is no direct way since this lib is independent from react.

But I believe there will be workaround:

Check this issue - It may give you directions - https://github.com/bumbeishvili/org-chart/issues/97

**Comment by vindx** [comment]
i tried "renderToStaticMarkup" or "rendertostring" functions from "'react-dom/server" lib and it worked
![image](https://user-images.githubusercontent.com/48135880/150395942-15ef224b-584e-4700-abd6-d71fd84ab3c1.png)

**Comment by kkkasio** [comment]
> i tried "renderToStaticMarkup" or "renderToString" functions from "'react-dom/server" lib and it worked ![image](https://user-images.githubusercontent.com/48135880/150395942-15ef224b-584e-4700-abd6-d71fd84ab3c1.png)

Thanks, I'll study to do it the way you said.
today I have a totally static html in my JSX, I don't see any problem but my code is very ugly!😅

**Comment by marcellino-ornelas** [comment]
Want to use more react and less d3? check out this stackblitz link

https://stackblitz.com/edit/d3-org-chart-react-integration-hooks-2chluf?file=index.js,OrgChart.js

Instead of striping everything react away in the chart (`React.renderToString`) we were able to use this org chart but keep all react functionality by drawing the graph and linking react components to it by using [`createPortal`](https://reactjs.org/docs/portals.html)

Now you get the benefits of using this library to draw the graph but get all the benefits of react. We've been using this route for about 2 months now and have not run into any issues. We do use the basics of this graph (just draw the graph and thats it) although we do plan to implement some other functionality this library provides (centering, expanding, etc)
