### ISSUE TITLE
Tag releases in the repo

### ISSUE THREAD

**Issue by ajmas** [bumbeishvili/org-chart#192]
I wanted to investigate an issue, but it turns out the project does not tag releases. Releases are only tagged in the commit comments.

It would be good to create a new tag in git, that corresponds to a given release in npm.

**Comment by bumbeishvili** [comment]
@ajmas  I am unfamiliar with that workflow, can you write more details about it?

**Comment by ajmas** [comment]
If I look here you have 38 versions:

https://www.npmjs.com/package/d3-org-chart?activeTab=versions

But here you have two tags:

https://github.com/bumbeishvili/org-chart/tags

Ideally you’d have a tag for each release, for example:

V2.6.0
V2.6.1

that way to see the state of the source for a given release you just need to look at the corresponding tag. 

One article on this: https://www.gitkraken.com/gitkon/semantic-versioning-git-tags

In some of the projects I work on, we couple this with continuous integration, such that when a new tag is created a build process is created and on successful build a release is created. It is possible some people publish to npm as an extension, but I am not aware of specific cases.

**Comment by bumbeishvili** [comment]
@ajmas I remembered now that I was not trying to use releases or tags functionality at all. 

The initial purpose was the need to use `unpkg` or similar services which would load code in web-supported version. 

As it turned out, I could just use npm releases for this purpose, so I haven't updated tags and releases after that.

```javascript
<script src="https://cdn.jsdelivr.net/npm/d3-org-chart@2"></script>
```

NPM keeps track of all published versions here

https://www.npmjs.com/package/d3-org-chart?activeTab=versions

It's also possible to see version specific code 

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/6873202/209813828-a1dc329e-229b-4818-b2ed-568776d9a64b.png">

Or even include it via `jsDelivr` or similar services

```
https://cdn.jsdelivr.net/npm/d3-org-chart@2.4.0
```

Would not this help to investigate the issue? I am genuinely interested if it would be very different experience in case I actually used tags & releases per version published.
