### ISSUE TITLE
Support search for specific node and graph exploration from non-root node

### ISSUE THREAD

**Issue by guyrom** [bumbeishvili/org-chart#2]
Add search functionality that will provide relevant potential nodes. Then explore the graph from the chosen node enabling exploration towards the root and away from the root.

**Comment by bumbeishvili** [comment]
My Thinking : 

Search functionality should be done outside graph (we already have data and can do anything with it - create a search panel for example and use this data to search in it), so that won't be part of tree graph code 

On the other hand, I think some method should be exposed in  chart code, which will expand, center and highlight node based on passed ID

**Comment by bumbeishvili** [comment]
The new version is published, closing this.

You can get more info about the new org-chart version in this [Medium article](https://bumbeishvili.medium.com/introducing-a-new-org-chart-130368314f04)

**Comment by kasamkranthi** [comment]
Hi, how to start exploration from non-root node. Can you please provide more information. I tried to find the functionality from the code but couldn't figure it out
