### ISSUE TITLE
Discrepancy with typescript definition for onNodeClick

### ISSUE THREAD

**Issue by ryansukale** [bumbeishvili/org-chart#211]
**Describe the bug**
The typescript definition for `onNodeClick` shows `onNodeClick(): (node: HierarchyNode<Datum>) => void;` - [Source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-org-chart/index.d.ts#L165)

The actual code is invoked with the nodeId - https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L812

This is a bug because the attr definition also hints that this is supposed to be a node object - https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L95

Sending a node is more consistent with the other callback functions as well, instead of just the nodeId.

**Expected behavior**
The correct/consistent implementation [for this line](https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L812) would be `attrs.onNodeClick(data);`

**Comment by bumbeishvili** [comment]
I am not maintaining Typescript definitions, so, I'd suggest making relevant issue/pr in `definitely typed` repo

**Comment by ryan-addepar** [comment]
ok. My suggestion is that it would be more consistent for the code to send down the `attrs.onNodeClick(data);` as it does the same in all the other functions.

In the code, even when i look at the attrs object, it uses the variable "d" - https://github.com/bumbeishvili/org-chart/blob/master/src/d3-org-chart.js#L95

In all the other functions "d" represents the node itself.
Only in this function "d" seems to be invoked with nodeId instead of the `data`. So this line causes confusion.

**Comment by bumbeishvili** [comment]
I agree with you on this one. I think it was already suggested , but don't remember where, will keep this issue open and will make relevant changes when publishing a new version

**Comment by m-gallesio** [comment]
@ryansukale @ryan-addepar
I am currently working on revamping the TypeScript definitions of this package, in which I have included this fix.

**Comment by m-gallesio** [comment]
@ryansukale @ryan-addepar @bumbeishvili This is now completed and published on NPM.
