### ISSUE TITLE
expanded not working

### ISSUE THREAD

**Issue by mosi-yazilim** [bumbeishvili/org-chart#217]
whatever happens expanded not working. I try everyhing!

I guess d3.v7 problem

all i want is to run it

![click](https://user-images.githubusercontent.com/84375411/210962052-f7d753dd-d643-4243-a1ab-c294f509cde0.JPG)

**Comment by bumbeishvili** [comment]
Can you share a reproducible example?

You can expand this sample 

https://stackblitz.com/edit/web-platform-jyncb9?file=index.html

**Comment by jlagunilla** [comment]
Hi David, in your example in https://stackblitz.com/edit/web-platform-jyncb9?file=index.html, I've tried to type the following in the console:

chart.setExpanded('O-6068').render();

but nothing happens. Shouldn't the chart be rerendered with this particular node expanded?

Thank you!

**Comment by bumbeishvili** [comment]
It should

**Comment by jlagunilla** [comment]
I know, I've checked the source code. Any idea about what might be happening?

**Comment by jlagunilla** [comment]
Just to keep you updated, this works:

const node = attrs.allNodes.filter(({ data }) => attrs.nodeId(data) == 'O-6068')[0];
// Simulate a click to expand children.
chart.onButtonClick( null, node );

I can't see why this works instead of

chart.setExpanded('O-6068').render();

which should be the preferred way to set expand a node programatically.

**Comment by jamespeek** [comment]
I encountered this bug today too; it appears to work to collapse a node, but not expand it.

I created a fork of the suggested stackblitz: 

https://stackblitz.com/edit/web-platform-kxhxdtgb?file=index.html

As you can see the centering on the node works, but it does not expand it.
