### ISSUE TITLE
why does the original node moves from it's place when the expand button is clicked?

### ISSUE THREAD

**Issue by akshay-developer-2021** [bumbeishvili/org-chart#303]
how to stop it? it makes it hard to focus on the original node, and the animation is too fast, and not sure how we can customize the animation speed or stop the node from moving altogether.

**Comment by bumbeishvili** [comment]
1. It moves because by default active is centered, set it to `chart.setActiveNodeCentered(false)` to disable movement

https://github.com/bumbeishvili/org-chart/blob/279153efe64de34f011db458f7f2655884a2fef0/src/d3-org-chart.js#L68

2. You can override duration to slow down animation

https://github.com/bumbeishvili/org-chart/blob/279153efe64de34f011db458f7f2655884a2fef0/src/d3-org-chart.js#L66
