### ISSUE TITLE
Straight lines

### ISSUE THREAD

**Issue by NemanjaRCT** [bumbeishvili/org-chart#372]
Hi, I want to make connection lines between nodes straight. 
I saw in earlier discussions that the solution can be overriding diagonal function. Is it possible to override it even though org-chart is used through node modules? I would not like to include the entire code in my project.
As a context - I am using it inside of an angular app

**Comment by bumbeishvili** [comment]
Yes, it's possible

You can override `chart.linkGroupArc` and instead of `d3.linkHorizontal`, use `d3.link(d3.curveLinear)`

```javascript
 chart.linkGroupArc(function linkValue({ source, target }) {
        const linkGenerationFunc = d3.link(d3.curveLinear)
          .x((d) => d.x)
          .y((d) => d.y);

        return linkGenerationFunc({
          source: { x: source.x, y: source.y + 30 },
          target: target,
        });
      })
```


<img width="460" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/9ace294c-30a5-474e-930a-17aa725ab643">

https://stackblitz.com/edit/js-w8sunj?file=index.html

You might also like to use d3.link(d3.curveStep)

<img width="406" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/b389f9ac-bfa5-4fc1-826f-c9a3e4c48795">

**Comment by NemanjaRCT** [comment]
@bumbeishvili  Thanks for the answer, but my question was about the lines between the nodes
<img width="640" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/163058588/26dd5908-5bfa-4427-968b-a32bd97f475e">

**Comment by bumbeishvili** [comment]
Ah, in that case you can override pretty complex diagonal function and set `rdef` to 0 instead of 35

<img width="262" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/00ea247c-33f8-4625-a704-11752417204b">


```javascript
chart.diagonal(function (s, t, m, offsets = { sy: 0 }) {
      const x = s.x;
      let y = s.y;

      const ex = t.x;
      const ey = t.y;

      let mx = m && m.x != null ? m.x : x; // This is a changed line
      let my = m && m.y != null ? m.y : y; // This also is a changed line

      let xrvs = ex - x < 0 ? -1 : 1;
      let yrvs = ey - y < 0 ? -1 : 1;

      y += offsets.sy;

      let rdef = 0;
      let r = Math.abs(ex - x) / 2 < rdef ? Math.abs(ex - x) / 2 : rdef;

      r = Math.abs(ey - y) / 2 < r ? Math.abs(ey - y) / 2 : r;

      let h = Math.abs(ey - y) / 2 - r;
      let w = Math.abs(ex - x) - r * 2;
      //w=0;
      const path = `
                          M ${mx} ${my}
                          L ${x} ${my}
                          L ${x} ${y}
                          L ${x} ${y + h * yrvs}
                          C  ${x} ${y + h * yrvs + r * yrvs} ${x} ${
        y + h * yrvs + r * yrvs
      } ${x + r * xrvs} ${y + h * yrvs + r * yrvs}
                          L ${x + w * xrvs + r * xrvs} ${
        y + h * yrvs + r * yrvs
      }
                          C  ${ex}  ${y + h * yrvs + r * yrvs} ${ex}  ${
        y + h * yrvs + r * yrvs
      } ${ex} ${ey - h * yrvs}
                          L ${ex} ${ey}
               `;
      return path;
    })
```

<img width="551" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/d225ee29-3e71-4b2e-b816-069592a91a37">


https://stackblitz.com/edit/js-wzb3tw?file=index.html

**Comment by bumbeishvili** [comment]
If you want straight lines like this

<img width="514" alt="image" src="https://github.com/bumbeishvili/org-chart/assets/6873202/00869081-1d2c-43be-bef3-710ebb800557">

You can return relevant path
```javascript
  const path = `
                          M ${x} ${y}
                          L ${ex} ${ey}
               `;
```

https://stackblitz.com/edit/js-vn3cza?file=index.html

**Comment by NemanjaRCT** [comment]
Thanks again for your help @bumbeishvili. I will try these options

**Comment by fahry-mohammed** [comment]
I am using org-chart with react and how can I override the algorithm?
